/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SshRouteRouteImport } from './routes/ssh/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SshSettingsRouteImport } from './routes/ssh/settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SshRouteRoute = SshRouteRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SshSettingsRoute = SshSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SshRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ssh': typeof SshRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/ssh/settings': typeof SshSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ssh': typeof SshRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/ssh/settings': typeof SshSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ssh': typeof SshRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/ssh/settings': typeof SshSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ssh' | '/login' | '/ssh/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ssh' | '/login' | '/ssh/settings'
  id: '__root__' | '/' | '/ssh' | '/login' | '/ssh/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SshRouteRoute: typeof SshRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssh': {
      id: '/ssh'
      path: '/ssh'
      fullPath: '/ssh'
      preLoaderRoute: typeof SshRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssh/settings': {
      id: '/ssh/settings'
      path: '/settings'
      fullPath: '/ssh/settings'
      preLoaderRoute: typeof SshSettingsRouteImport
      parentRoute: typeof SshRouteRoute
    }
  }
}

interface SshRouteRouteChildren {
  SshSettingsRoute: typeof SshSettingsRoute
}

const SshRouteRouteChildren: SshRouteRouteChildren = {
  SshSettingsRoute: SshSettingsRoute,
}

const SshRouteRouteWithChildren = SshRouteRoute._addFileChildren(
  SshRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SshRouteRoute: SshRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
